import Link from "next/link"
import Header from "../../components/header"
import Head from "next/head"
import Image from "next/image"
import Footer from "../../components/footer"

export default function Tips() {
    return (
        <div class="container max-w-2xl mx-auto justify-center">
      <Head>
        <title>Crypto Escrow Tips | Yes Crow</title>
        <meta 
          name="description" 
          content="Get to trust internet strangers without worries. Self-release the payment when you get what you wanted." 
          />
        <link rel="canonical" href="https://yescrow.io/tips" />
      </Head>
        <Header />
        <main>
        <h1 class="m-4 text-4xl text-center font-bold">Crypto Escrow Tips</h1>
          <p class="m-4 text-xl text-center"><i>Yes Crow</i> is a decentralized escrow service that wants to help people make financial crypto transactions safely and comfortably.</p>
          <br/>
            <div class="flex m-4">
                <p class="m-4 text-4xl text-left font-bold border-b-4 hover:text-matrix"><Link href="/tips/how-to-not-get-scammed">How To Protect Yourself From Internet Scams?</Link></p>
                <Image layout="responsive" src="/internet_scammer.png" width="108" height="108" xmlns="http://www.w3.org/2000/svg" alt="internet scammer generated by AI"></Image>
            </div>
            <div class="flex m-4">
                <p class="m-4 text-4xl text-left font-bold border-b-4 hover:text-matrix"><Link href="/tips/escrow-usdt">Why Should You Escrow USDT Instead Of The Dollar?</Link></p>
                <Image layout="responsive" src="/neo_escrow.png" width="108" height="108" xmlns="http://www.w3.org/2000/svg" alt="matrix escrow generated by AI"></Image>
            </div>
        </main>
        <Footer />
        </div>
        
       
    )
}
    