import Link from "next/link"
import Header from "../../components/header"
import Head from "next/head"
import Image from "next/image"

export default function Tips() {
    return (
        <div class="container max-w-2xl mx-auto justify-center">
      <Head>
        <title>Escrow USDT or ETH - Ethereum Escrow Service | Yes Crow</title>
        <meta 
          name="description" 
          content="Get to trust internet strangers without worries. Self-release the payment when you get what you wanted." 
          //When transacting on the internet - use protection: the only way to trust a stranger online is to use an escrow. 
          key="desc"
          />
        <link rel="canonical" href="https://yescrow.io" />
      </Head>
        <Header />
        <main>
            <div class="flex m-4">
                <p class="m-4 text-4xl text-left font-bold border-b-4 hover:text-matrix"><Link href="/blog/how-to-not-get-scammed">How To Protect Yourself From Internet Scams?</Link></p>
                <Image src="/internet_scammer.png" width="108" height="108" viewBox="0 0 108 108" xmlns="http://www.w3.org/2000/svg" alt="internet scammer generated by AI"></Image>
            </div>
            <div class="flex m-4">
                <p class="m-4 text-4xl text-left font-bold border-b-4 hover:text-matrix"><Link href="/blog/escrow-usdt">Why Should You Escrow USDT Instead Of The Dollar?</Link></p>
                <Image src="/neo_escrow.png" width="108" height="108" viewBox="0 0 108 108" xmlns="http://www.w3.org/2000/svg" alt="matrix escrow generated by AI"></Image>
            </div>
        </main>
        </div>
       
    )
}
    